# Generated by Django 3.2.3 on 2021-05-23 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_instractor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instractor',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
