# Generated by Django 3.2.3 on 2021-06-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
