# Generated by Django 3.2.3 on 2021-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_student_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
