# Generated by Django 3.2.3 on 2021-07-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210724_1200'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user', 'name', 'email', 'course_enrolled', 'trx_id', 'date_of_birth', 'education_qualification', 'institution_name', 'image', 'student_address', 'payment_method'], name='account_stu_user_id_394d2f_idx'),
        ),
    ]
