# Generated by Django 3.2.3 on 2021-07-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_student_account_stu_user_id_394d2f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
