# Generated by Django 3.2.3 on 2021-07-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_student_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
    ]
