# Generated by Django 3.2.3 on 2021-07-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_batchnumber_course'),
        ('account', '0016_remove_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.batchnumber'),
        ),
    ]
