# Generated by Django 3.2.3 on 2021-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_student_batch_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='account_stu_user_id_394d2f_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='student',
            name='trx_id',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user', 'name', 'email', 'course_enrolled', 'date_of_birth', 'education_qualification', 'institution_name', 'image', 'student_address'], name='account_stu_user_id_b8973a_idx'),
        ),
    ]
