# Generated by Django 3.2.3 on 2021-06-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210601_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='regular_price',
            new_name='price',
        ),
    ]
