# Generated by Django 3.2.3 on 2021-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coupon_elasticdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limited',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
