# Generated by Django 3.2.3 on 2021-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_coupon_course'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name', 'image', 'category', 'offer_price', 'course_requirements', 'course_description', 'course_description', 'updated_at'], name='course_cour_name_e93be5_idx'),
        ),
    ]
