# Generated by Django 3.2.3 on 2021-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
